CREATE USER IDP IDENTIFIED BY MANAGER
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO IDP;
GRANT CREATE TABLE TO IDP;
GRANT CREATE VIEW TO IDP;
GRANT CREATE SEQUENCE TO IDP;
GRANT CREATE PROCEDURE TO IDP;
GRANT CREATE TRIGGER TO IDP;

ALTER USER IDP ACCOUNT UNLOCK;

ALTER USER IDP IDENTIFIED BY MANAGER;

GRANT EXECUTE ON DBMS_CRYPTO TO IDP;
GRANT EXECUTE ON DMS.SOC2_COMPLIANCE_PKG TO IDP;
GRANT SELECT ON DMS.SEC_AUTHENTICATION_LOG TO IDP;

-- If using the custom authentication function
GRANT EXECUTE ON DMS.fn_custom_authenticate TO IDP;
GRANT EXECUTE ON DMS.fn_validate_password TO IDP;
GRANT EXECUTE ON DMS.sp_change_password TO IDP;

PROMPT Granting DMS read access to IDP audit tables...

-- Core authentication tables (read-only)
GRANT SELECT ON IDP.AUTH_IDENTITY_PROVIDERS TO DMS;
GRANT SELECT ON IDP.AUTH_SAML_CONFIG TO DMS;
GRANT SELECT ON IDP.AUTH_LDAP_CONFIG TO DMS;
GRANT SELECT ON IDP.AUTH_CUSTOM_CONFIG TO DMS;
GRANT SELECT ON IDP.AUTH_TRUSTED_SERVICES TO DMS;
GRANT SELECT ON IDP.AUTH_GROUP_ROLE_MAP TO DMS;

-- User identity and session tables
GRANT SELECT ON IDP.AUTH_FEDERATED_IDENTITIES TO DMS;
GRANT SELECT ON IDP.AUTH_SSO_SESSIONS TO DMS;

-- Audit log (critical for SOC2 reports)
GRANT SELECT ON IDP.AUTH_FEDERATION_LOG TO DMS;

-- MFA tables (for MFA status reporting)
GRANT SELECT ON IDP.AUTH_MFA_CONFIG TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_ENROLLMENT TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_BACKUP_CODES TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_TRUSTED_DEVICES TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_CHALLENGES TO DMS;

-- Views
GRANT SELECT ON IDP.AUTH_PROVIDERS_VW TO DMS;
GRANT SELECT ON IDP.AUTH_ACTIVE_SESSIONS_VW TO DMS;
GRANT SELECT ON IDP.AUTH_FEDERATION_STATS_VW TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_STATUS_VW TO DMS;
GRANT SELECT ON IDP.AUTH_MFA_FAILED_ATTEMPTS_VW TO DMS;

PROMPT Granted: DMS can read IDP audit logs for SOC2 reporting

-- ============================================================================
-- SECTION 3: Allow DMS to call IDP for validation
-- ============================================================================

PROMPT Granting DMS access to IDP packages...

-- Allow DMS to call IDP authentication (for custom APEX auth)
GRANT EXECUTE ON IDP.federated_auth_pkg TO DMS, APEX_PUBLIC_USER;
GRANT EXECUTE ON IDP.mfa_auth_pkg TO DMS;
GRANT EXECUTE ON IDP.idp_dms_bridge_pkg TO DMS;

PROMPT Granted: DMS can call IDP authentication packages

