-- Synonyms in IDP schema for DMS objects
CREATE OR REPLACE SYNONYM IDP.SOC2_PKG 
    FOR DMS.SOC2_COMPLIANCE_PKG;

CREATE OR REPLACE SYNONYM IDP.DMS_AUTH_LOG 
    FOR DMS.SEC_AUTHENTICATION_LOG;

CREATE OR REPLACE SYNONYM IDP.DMS_SESSIONS 
    FOR DMS.SEC_ACTIVE_SESSIONS;

PROMPT Created synonyms for cross-schema access