CREATE USER IDP IDENTIFIED BY MANAGER
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO IDP;
GRANT CREATE TABLE TO IDP;
GRANT CREATE VIEW TO IDP;
GRANT CREATE SEQUENCE TO IDP;
GRANT CREATE PROCEDURE TO IDP;
GRANT CREATE TRIGGER TO IDP;

ALTER USER IDP ACCOUNT UNLOCK;

ALTER USER IDP IDENTIFIED BY MANAGER;

GRANT EXECUTE ON DBMS_CRYPTO TO IDP;
